name: Autograding Tests
'on':
  - repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Move tests
      run: rm -rf tests/ && mv tests ../../tests
    - name: Move .ok file
      run: rm ses02.ok && mv ses02.py ../../ses02.py
    - name: Move test script
      run: mv ok_to_pytest.py ../../test_ok.py
    - name: Python test
      id: python-test
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 1
        setup-command: 'pip install pandas==2.1.4 jupyter==1.0.0 networkx==3.2.1'
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        PYTHON-TEST_RESULTS: "${{steps.python-test.outputs.result}}"
      with:
        runners: python-test